ci: Enforce conventional commit format in PR title
probabl-ai/skore pull request #398
Opened 2024-09-24 14:21 UTC by augustebaum

- Add commitlint workflow to lint the PR title (not the individual PR commits)
- Make sentence-case the only allowed PR title format (first letter must be capitalized, like "Merge commit ..." or "Revert commit ...")

Closes #66

2024-09-30 14:17 UTC, augustebaum commented on .github/workflows/lint-pr-title.yml
> +      - uses: actions/checkout@v4
i only need the commitlint config file, and the permissions thing still allows the workflow to run. Good catches!

2024-09-30 14:54 UTC, tuscland submitted a review, later dismissed

2024-10-01 06:52 UTC, rouk1 submitted a review, later dismissed

2024-10-01 07:44 UTC, thomass-dev requested changes

2024-10-01 07:44 UTC, thomass-dev commented on .commitlintrc.yml
> +  "subject-case": [2, "always", ["sentence-case"]]
Is it possible to pass these parameters in the command line?
Aren't these parameters used only in the workflow? Will they be used by a dev? In my opinion, i don't think so.

2024-10-01 08:36 UTC, thomass-dev approved these changes
Nice work! I like it.

2024-10-01 08:37 UTC, merged