fix: Temporarily disable skops's security feature used in `SklearnBaseEstimatorItem`
probabl-ai/skore pull request #420
Opened 2024-10-01 13:59 UTC by thomass-dev

2024-10-01 14:47 UTC, rouk1 submitted a review, later dismissed
Sounds good to me but I do not know how to build a "unsafe" estimator.

2024-10-01 15:13 UTC, thomass-dev commented
Please @tuscland can you take a look? Thanks.

2024-10-01 15:16 UTC, tuscland requested changes
Overall that's looking great, however I would like to see a test succeeding in the case of an otherwise untrusted estimator.

2024-10-02 09:04 UTC, augustebaum approved these changes

2024-10-02 09:12 UTC, tuscland approved these changes

2024-10-02 09:38 UTC, merged