feat: Add a convenient way of outputting system and dependency versions (#425)
probabl-ai/skore pull request #426
Opened 2024-10-02 11:53 UTC by tuscland

2024-10-02 15:10 UTC, rouk1 requested changes

2024-10-02 15:10 UTC, rouk1 commented on src/skore/utils/_show_versions.py
> +    ]
You may use the built-in toml parser to read this from the pyproject.toml file.

```python
import tomllib

with open("pyproject.toml", "rb") as f:
    data = tomllib.load(f)
    print(data["project"]["dependencies"])
```

2024-10-02 15:41 UTC, rouk1 requested changes

2024-10-02 15:41 UTC, rouk1 commented on src/skore/utils/_show_versions.py
> +    with open("pyproject.toml", "rb") as f:
I suppose that this path should be computed from the `__file__` variable. 
@thomass-dev will the pyproject.toml be there in a release ?

2024-10-03 08:33 UTC, rouk1 commented
The `_get_deps_info` function now uses `importlib` instead of parsing the `pyproject`.
co-autorhed with @thomass-dev

2024-10-03 08:34 UTC, thomass-dev approved these changes

2024-10-03 08:37 UTC, rouk1 approved these changes

2024-10-03 08:37 UTC, merged