feat(UI): Clarify how items can be added to a view
probabl-ai/skore pull request #542
Opened 2024-10-18 15:19 UTC by rouk1

This PR
- disable double click action
- add optional actions to accordion items
- plug + action to the display key project's store action

UI preview:

https://github.com/user-attachments/assets/c6df8dd6-03ea-4fcd-a254-2eb8747d3d35

2024-10-18 16:24 UTC, tuscland commented
I checked out this branch, have an empty view selected, but when I click the + button it does not add the item to the view. Dragging works though.

2024-10-18 16:27 UTC, tuscland requested changes
See my comment, for me the + button did not work properly.

2024-10-21 08:39 UTC, rouk1 commented
> I checked out this branch, have an empty view selected, but when I click the + button it does not add the item to the view. Dragging works though.
> click-item.mov

Is there some errors in the js console ? I cant reproduce this on my side ?

note: code as been merged

2024-10-21 13:57 UTC, tuscland approved these changes

2024-10-21 15:09 UTC, merged